### ISSUE TITLE
Enhance documentation with more examples 

### ISSUE THREAD

**Issue by Andrei-Cornea** [niksy/postcss-query-ast#2]
Hi @niksy,

I'm using your npm module **stylelint-no-restricted-syntax**, that it's using this module as a dependency.

Would be really great, if you can enhance the examples from the Readme, as it's a struggle to use it.

I'm referring to these examples
 
Type selectors: rule, atrule, decl, comment
Universal selector: *
Attribute selectors: [attr=value], [attr=value], [attr~=value], [attr|=value], [attr^=value], [attr$=value], [attr*=value]
Descendant combinator: rule decl
Child combinator: atrule > rule
Adjacent sibling combinator: rule + rule
General sibling combinator: rule ~ rule
Child pseudo classes (:first-child, :last-child, :nth-child, :nth-last-child, :only-child): rule:first-child
Type pseudo classes (:first-of-type, :last-of-type, :nth-of-type, :nth-last-of-type, :only-of-type): rule:first-of-type
Empty nodes: rule:empty
Matches: :matches(rule, atrule)
Negation: :not(atrule)

How to use the Type selectors, what values can be used inside: rule,atrule,decl,comment.
How many params can be used for example "selector": "decl[prop='z-index']",
Checking out https://postcss.org/api/#declaration  the class Declaration accepts more parameters. 
I that possible as well? eg: "selector": "decl[prop='z-index' value='test']",

In my case i want to restrict the usage of extend in less files

```
Case 1
  .a:extend(.b) {}
Case 2
   .a {
     &:extend(.b);
   }
```

Here is my config until now. 
At the moment i'm checking PostCSS API documentation to figure out what params can be used inside Type selectors.
The first case is handled, not sure how can fix the second case. For sure it can be done with **Descendant combinator: rule decl**
not sure yet how that translates into a correct syntax 

```
  {
        "selector": "rule[selector='/:extend/ig']", // disallow less extend
        "message": "extend not allowed."
    },
    {
        "selector": "decl[value='extend']",
        "message": "z-index not allowed."
    }
```

Thanks in advance for your time !

**Comment by niksy** [comment]
Hi @Andrei-Cornea, thanks for the comment!

I tried to keep documentation to minimum just like ESLint does and I think it covers most of the cases.

As for your questions:

> How to use the Type selectors, what values can be used inside?

Any node property value can be used.

> How many params can be used for example "selector": "decl[prop='z-index']",
Checking out postcss.org/api/#declaration the class Declaration accepts more parameters.
I that possible as well? eg: "selector": "decl[prop='z-index' value='test']",

You can achieve that just like standard CSS selector: `decl[prop='z-index'][value='test']`

If you have idea how can I make documentation more detailed, I’m open to changes!

**Comment by Andrei-Cornea** [comment]
Hi @niksy, thanks for your reply. 
This being the first time around AST syntax maybe was a bit confusing.
What helped a lot was unit tests examples.

Maybe the easiest would be to just add those examples as well here.
The best would be to have an css/scss example as well, to have a better understanding of the use case, if is not too much to ask.
Here is a small example of universal selector, how i see the quick way without css example 

Universal selector: * 
```
1.  '* decl'
2. '* [value="lightgreen"]'
3. '* *'
```

Thanks again for your help.
Best Andrei

**Comment by niksy** [comment]
I could add sentence to check tests for more examples. Does that sound OK to you?

**Comment by Andrei-Cornea** [comment]
Yes, should be fine.

**Comment by niksy** [comment]
@Andrei-Cornea I see that you closed this issue, sorry I forgot about it! Did you manage to understand better how this module works?
